apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ logstash_configmap_pipeline.name }}"
  namespace: "{{ logstash_configmap_pipeline.namespace }}"
data:
  {{ logstash_configmap_pipeline.name }}.conf: |-
    input {
      tcp {
        port => 5044
        codec => "json"
      }
    }
    output {
      elasticsearch {
        hosts => "elasticsearch:9200"
        index => "logstash-%{+YYYY.MM.dd}"
        sniffing => false
      }
    }
