apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ item.name }}"
  namespace: "{{ item.namespace }}"
data:
  logstash.yml: |-
    path.config: {{ logstash_path_config }}
    config.debug: {{ logstash_config_debug }}
    queue.type: {{ logstash_queue_type }}
{% if logstash_queue_type == 'persisted' %}
    path.queue: {{ logstash_path_queue }}
    queue.page_capacity: {{ logstash_queue_page_capacity }}
    queue.max_events: {{ logstash_queue_max_events }}
    queue.max_bytes: {{ logstash_queue_max_bytes }}
    queue.checkpoint.acks: {{ logstash_queue_checkpoint_acks }}
    queue.checkpoint.writes: {{ logstash_queue_checkpoint_writes }}
    queue.checkpoint.interval: {{ logstash_queue_checkpoint_interval }}
{% endif%}
    http.host: "{{ logstash_http_host }}"
    http.port: {{ logstash_http_port }}
