apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ logstash_deployment.name }}"
  namespace: "{{ logstash_deployment.namespace }}"
spec:
  replicas: {{ logstash_deployment.replicas }}
  selector:
    matchLabels:
      app: "{{ logstash_deployment.name }}"
  template:
    metadata:
      labels:
        app: "{{ logstash_deployment.name }}"
    spec:
      containers:
      - image: "{{ logstash_deployment.image }}"
        name: "{{ logstash_deployment.name }}"
        ports:
{% for port in logstash_deployment.ports %}
          - name: {{ port.name }}
            containerPort: {{ port.containerPort }}
{% endfor %}
        volumeMounts:
        - name: config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
          readOnly: true
        - name: pipeline
          mountPath: /usr/share/logstash/pipeline
          readOnly: true

      volumes:
      - name: pipeline
        configMap:
          name: "{{ logstash_deployment.name }}-pipeline"
          logstash_deployments:
          - key: pipeline.conf
            path: pipeline.conf
      - name: config
        configMap:
          name: "{{ logstash_deployment.name }}-config"
          logstash_deployments:
          - key: logstash.yml
            path: logstash.yml
