apiVersion: v1
kind: Service
metadata:
  name: "{{ logstash_deployment.name }}"
  namespace: "{{ logstash_deployment.namespace }}"
spec:
  type: NodePort
  selector:
    app: "{{ logstash_deployment.name }}"
  ports:
{% for port in logstash_deployment.ports %}
    - name: "{{ port.name }}"
      port: {{ port.containerPort }}
      targetPort: {{ port.containerPort }}
      protocol: TCP
{% endfor %}
