apiVersion: v1
kind: Service
metadata:
name: "{{ item.name }}"
namespace: "{{ item.namespace }}"
spec:
  type: NodePort
  selector:
    app: "{{ item.name }}"
  ports:
  - name: "{{ item.name }}"
    port: "{{ item.port }}"
    targetPort: "{{ item.port }}"
    protocol: TCP
