---

java_version: "openjdk-8-jdk-headless"

logstash_major_version: "6.x"
logstash_version: "6.2.3"
logstash_apt_key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
logstash_apt_url: "deb https://artifacts.elastic.co/packages/{{ logstash_major_version }}/apt stable main"
logstash_user: logstash
logstash_group: logstash
logstash_conf_dir: "/opt/logstash"
logstash_log_dir: "/var/log/logstash"
logstash_reload_automatic: true
#logstash_plugin:
